config/routes.rb
Rails.application.routes.draw do
	root 'quotes#index'
	resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quotes = Quote.new
  end

  def create
    @quotes = Quote.new(params.require(:quote).permit(:quote))

    respond_to do |format|
      if @quotes.save
        format.html { redirect_to quotes_path, notice: 'Your quote has been added!' }
      else
        format.html { render :new }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuotationApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<h1 align="center">Here we go with quotes!</h1>

<p align="center"><%= link_to "Add New Quote", new_quote_path %></p>
<hr>

<% @quotes.each do |quotes| %>
  <p><i><%= quotes.quote %></i></p>
  <hr>
<% end %>

app/views/quotes/new.html.erb
<style> 
input[type=text] {
    width: 25%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: 2px solid red;
    border-radius: 4px;
}
</style>


<h1 align="center">Add a new quote!</h1>

<%= form_for(@quotes) do |form| %>
  <div class="field" align="center" >
    <%= form.label :quote %>
    <%= form.text_field :quote %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>